[package]
name = "nbr"
version = "0.4.3"
edition = "2024"
description = "CLI for NoneBot2 - A Rust implementation"
license = "MIT"
repository = "https://github.com/nonebot/nbr"
readme = "README.md"
keywords = ["nonebot", "cli", "chatbot", "bot", "nbr"]
categories = ["command-line-utilities"]

[package.metadata]
authors = [{ name = "fllesser", email = "fllessive@gmail.com" }]

[[bin]]
name = "nbr"
path = "src/main.rs"

[dependencies]
# CLI framework
clap = { version = "4.6.1", features = ["derive", "color", "suggestions"] }

# Async runtime
tokio = { version = "1.52.3", features = [
  "signal",
  "process",
  "rt-multi-thread",
  "macros",
] }

# HTTP client
reqwest = { version = "0.13.3", features = [
  "json",
  "rustls",
  "stream",
], default-features = false }

# Serialization
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
# serde_yaml = "0.9"

# TOML handling
toml = "1.1.2+spec-1.1.0"

# Terminal UI and progress bars
indicatif = "0.18.4"
console = "0.16.3"
dialoguer = "0.12.0"

# Error handling
anyhow = "1.0.102"
thiserror = "2.0.18"

# Git operations
# git2 = { version = "0.20.2", default-features = false }

# Directory management
directories = "6.0.0"

# Regex support
regex = "1.12.3"

# File watching
notify = "8.2.0"

# System information
sysinfo = { version = "0.39.2", features = ["disk"] }

# Futures utilities
futures-util = "0.3.32"

# Logging
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = [
  "env-filter",
  "time",
  "ansi",
] }

toml_edit = "0.25.11+spec-1.1.0"
tracing-core = "0.1.36"
ansi_term = "0.12.1"
strum = { version = "0.28.0", features = ["derive"] }

[dev-dependencies]
tempfile = "3.27.0"
insta = { version = "1.47.2", features = ["yaml", "redactions"] }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
