name: Publish to Cargo
on:
  push:
    tags: ["v*"]

jobs:
  publish:
    runs-on: ubuntu-latest

    name: "publish"

    # Reference your environment variables
    environment: cargo

    strategy:
      fail-fast: false
      matrix:
        include:
          - dir: "/nb-cli-rust"
            tag_prefix: "v"
    steps:
      - uses: actions/checkout@master
        with:
          # get git tags info
          fetch-depth: 0

      - name: Run publish-action
        uses: tu6ge/publish-action@v0.4.5
        env:
          # This can help you tagging the github repository
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # This can help you publish to crates.io
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        with:
          DIR: ${{ matrix.dir }}
          TAG_PREFIX: ${{ matrix.tag_prefix }}
